# Generated by Django 4.2.4 on 2023-12-08 23:45

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', api.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', api.CharField(max_length=255, verbose_name='CPF/CNPJ')),
                ('nome', api.CharField(max_length=255, verbose_name='Nome')),
                ('endereco', api.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('telefone', api.CharField(max_length=255, verbose_name='Telefone')),
                ('cpf_responsavel', api.CharField(max_length=255, verbose_name='CPF do Responsável')),
                ('nome_responsavel', api.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('cargo_responsavel', api.CharField(max_length=255, verbose_name='Cargo do Responsável')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', api.CharField(max_length=255, verbose_name='Descrição')),
                ('cor', api.CharField(max_length=255, verbose_name='Cor')),
                ('prazo_resposta', models.IntegerField(help_text='Em horas', verbose_name='Prazo para Resposta')),
            ],
            options={
                'verbose_name': 'Prioridade',
                'verbose_name_plural': 'Prioridades',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', api.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', api.CharField(max_length=255, verbose_name='Descrição')),
                ('assunto', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='gv.assunto', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', api.CharField(max_length=255, verbose_name='CPF')),
                ('nome', api.CharField(max_length=255, verbose_name='Nome')),
                ('assuntos', api.ManyToManyField(to='gv.assunto', verbose_name='Assuntos')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Consultante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', api.CharField(max_length=255, verbose_name='CPF')),
                ('nome', api.CharField(max_length=255, verbose_name='Nome')),
                ('cliente', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultantes', to='gv.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Consultante',
                'verbose_name_plural': 'Consultantes',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionamento', api.TextField(verbose_name='Pergunta')),
                ('data_pergunta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Pergunta')),
                ('resposta', api.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('consultante', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gv.consultante', verbose_name='Consultante')),
                ('especialista', api.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gv.especialista', verbose_name='Especialista')),
                ('prioridade', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gv.prioridade', verbose_name='Prioridade')),
                ('topico', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gv.topico', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_contrato',
            field=api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gv.tipocontrato', verbose_name='Tipo de Contrato'),
        ),
    ]
