# Generated by Django 4.2.4 on 2023-12-11 08:25

import api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observacao',
            field=api.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
