# Generated by Django 4.2.4 on 2023-12-11 09:01

import api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0002_consulta_observacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='questionamento',
            new_name='pergunta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='pergunta_ia',
            field=api.TextField(blank=True, null=True, verbose_name='Pergunta I.A.'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='resposta_ia',
            field=api.TextField(blank=True, null=True, verbose_name='Resposta I.A.'),
        ),
    ]
