# Generated by Django 4.2.4 on 2023-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0003_rename_questionamento_consulta_pergunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Consulta'),
        ),
    ]
