# Generated by Django 4.2.4 on 2023-12-11 09:33

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0004_consulta_data_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', api.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data do Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('cliente', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='gv.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
