# Generated by Django 4.1 on 2024-01-06 07:30

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0006_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', api.CharField(max_length=255, verbose_name='Sigla')),
                ('nome', api.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_contrato',
        ),
        migrations.AddField(
            model_name='cliente',
            name='assuntos',
            field=api.ManyToManyField(blank=True, to='gv.assunto', verbose_name='Assuntos'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='email',
            field=api.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='endereco',
            field=api.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='minicurriculo',
            field=api.TextField(blank=True, null=True, verbose_name='Minicurrículo'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='registro',
            field=api.CharField(blank=True, max_length=255, null=True, verbose_name='Nº do Registro Profissional'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='telefone',
            field=api.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
        migrations.DeleteModel(
            name='TipoContrato',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=api.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gv.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='estados',
            field=api.ManyToManyField(to='gv.estado', verbose_name='Estados'),
        ),
    ]
