# Generated by Django 4.1 on 2024-01-06 09:01

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0007_estado_remove_cliente_tipo_contrato_cliente_assuntos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', api.CharField(max_length=255, verbose_name='Mensagem')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('consulta', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='gv.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', api.CharField(max_length=255, verbose_name='Nome')),
                ('observacao', api.TextField(verbose_name='Observação')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('consulta', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='gv.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
