# Generated by Django 4.1 on 2024-01-06 10:11

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0009_anexo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunto',
            name='codigo_openai',
            field=api.CharField(blank=True, max_length=255, null=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', api.CharField(max_length=255, verbose_name='Nome')),
                ('arquivo', models.FileField(null=True, upload_to='arquivos', verbose_name='Arquivo')),
                ('codigo_openai', api.CharField(blank=True, max_length=255, null=True, verbose_name='Código')),
                ('assunto', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='gv.assunto', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
