# Generated by Django 4.1 on 2024-01-06 10:42

import api
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0010_assunto_codigo_openai_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='codigo_openai',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='topico',
            field=api.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='gv.topico', verbose_name='Tópico'),
        ),
        migrations.AddField(
            model_name='topico',
            name='codigo_openai',
            field=api.CharField(blank=True, max_length=255, null=True, verbose_name='Código'),
        ),
    ]
