# Generated by Django 4.1 on 2024-01-06 22:23

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0011_remove_arquivo_assunto_remove_assunto_codigo_openai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', api.CharField(max_length=255, verbose_name='Pergunta')),
                ('resposta', api.TextField(blank=True, verbose_name='Resposta')),
                ('topico', api.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='gv.topico', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.DeleteModel(
            name='Conteudo',
        ),
    ]
